name: MLOps CI 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Model Validation (Deepchecks)
      run: python ci_cd/validation.py
    
    - name: Upload Deepchecks Report to GitHub Pages
      if: always()
      run: |
        mkdir -p gh-pages
        mv deepchecks_report.html gh-pages/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages

    - name: Train model
      run: |  
        python ci_cd/train.py

    - name: Save the trained model
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: model/house_regression_model.pkl
         